### ISSUE TITLE
connection refused

### ISSUE THREAD

**Issue by nicedevil007** [bvmensvoort/node-red-contrib-philips-air#5]
heya, trying your example with right IP adresses of our philips devices.

I use http and I get this error all the time:

![grafik](https://user-images.githubusercontent.com/17103076/98217866-5f7d7d80-1f4b-11eb-97ba-dce16d0301c7.png)

all devices are AC3033/10

We use node-red inside a docker container.

**Comment by bvmensvoort** [comment]
Allright, it seems that the node can reach the IP. Otherwise you would have gotten the message: Host Unreachable.
So it looks like the Docker configuration is fine.

Then, can you access the AC3033/10 with the Air Matters App? 
Maybe it is not connected yet.

Second, it could be that the protocol is not http, but CoAP.

Note, accessing the URL in the browser, like http://192.168.194.36:80, results in a timeout.

If connecting works, but you have the messages occasionaly, maybe there is a pattern. For example when night mode is active on the ACdevice.

This node is just a passthrough to the Philips Air Node Library. Maybe there are some solutions there.

**Comment by networkpotato** [comment]
I am also running Node-RED inside Docker and get the same error. If I try using CoAP I get the following error instead:

`Error: Cannot communicate with the Philips device yet. Some software needs to be installed. To see which Python3 packages are needed, go to: https://developer.aliyun.com/mirror/npm/package/philips-air. The original error message: Error: Command failed: python3 /data/node_modules/philips-air/pyaircontrol.py --ipaddr 192.168.30.19 --protocol plain_coap --status
Traceback (most recent call last):
  File "/data/node_modules/philips-air/pyaircontrol.py", line 8, in <module>
    from pyairctrl.coap_client import CoAPAirClient
ModuleNotFoundError: No module named 'pyairctrl'`

**Comment by bvmensvoort** [comment]
Okay, it has been some time ago for me. I see the URL in the error message doesn't exist anymore.
I think it should lead to: https://www.npmjs.com/package/philips-air
There you will find instructions which software needs to be installed.
Hopefully this will point into the right directions for you.

Unfortunately, I don't have a CoAP myself, so I can't help you with specifics.

**Comment by networkpotato** [comment]
Well how do I install those packages inside the Node-RED Docker container? Those commands do not work from the container console (Portainer).

**Comment by bvmensvoort** [comment]
Sorry, I can't help you with specifics for the Python packages.
A pull request with a solution is welcome.

**Comment by networkpotato** [comment]
Got it working by installing the packages inside the Docker container.

**Comment by bvmensvoort** [comment]
Thanks for updating the issue!
